/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Database.DatabaseConnection;
import codigoFonte.ModeloTabela;
import java.awt.CardLayout;
import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TabableView;
import static oracle.net.aso.b.c;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Letícia Magalhães
 */
public class Cadastros extends javax.swing.JFrame {

    DatabaseConnection databaseConnection = new DatabaseConnection();

    /**
     * Creates new form Cadastros
     */
    public Cadastros() {
        initComponents();

        String[] vetor = {" ","30 Minutos","35 Minutos", "40 Minutos","45 Minutos", "1 Hora", "2 Horas" };

        txtDuracaoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(vetor));

        /*String[] opcoes = new String[3];
        
        opcoes[0] = "a";
        opcoes[1] = "b";
        opcoes[2] = "c";
        
        
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(opcoes));*/
    }

    private void mostrarTelas(String nome) {

        CardLayout card = (CardLayout) PainelPrincipal2.getLayout();
        card.show(PainelPrincipal2, nome);
    }

    private void mostrarImagem(String nome) {

        CardLayout card1 = (CardLayout) PainelPrincipal3.getLayout();
        card1.show(PainelPrincipal3, nome);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal1 = new javax.swing.JPanel();
        btnCadastrosUsuarios = new javax.swing.JButton();
        btnCadastrosMedicos = new javax.swing.JButton();
        btnCadastrosConsultorios = new javax.swing.JButton();
        btnCadastrosConvenios = new javax.swing.JButton();
        btnHeartClinCadastros = new javax.swing.JButton();
        PainelPrincipal3 = new javax.swing.JPanel();
        ImagemCadastrosMedicos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ImagemCadastrosConsultorios = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        ImagemCadastrosConvenios = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        ImagemCadastrosUsuarios = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        PainelPrincipal2 = new javax.swing.JPanel();
        PainelCadastrosUsuario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnSalvarUsuarios = new javax.swing.JButton();
        btnCancelarUsuarios = new javax.swing.JButton();
        btnEditarUsuarios = new javax.swing.JButton();
        btnExcluirUsuarios = new javax.swing.JButton();
        btnAtualizarUsuarios = new javax.swing.JButton();
        PainelCadastrosMedicos = new javax.swing.JPanel();
        btnSalvarMedico = new javax.swing.JButton();
        btnCancelarMedico = new javax.swing.JButton();
        btnEditarMedico = new javax.swing.JButton();
        btnExcluirMedico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeMedico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtClinicas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCRM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtIDMedico = new javax.swing.JTextField();
        txtEspecialidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMedicosScroll = new javax.swing.JScrollPane();
        TabelaMedicos = new javax.swing.JTable();
        txtDuracaoConsulta = new javax.swing.JComboBox<>();
        btnAtualizarMedico = new javax.swing.JButton();
        PainelCadastrosConsultorios = new javax.swing.JPanel();
        btnSalvarConsultorios = new javax.swing.JButton();
        btnCancelarConsultorios = new javax.swing.JButton();
        btnEditarConsultorios = new javax.swing.JButton();
        btnExcluirConsultorios = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnAtualizarConsultorios = new javax.swing.JButton();
        PainelCadastrosConvenios = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        btnSalvarConvenios = new javax.swing.JButton();
        btnCancelarConvenios = new javax.swing.JButton();
        btnEditarConvenios = new javax.swing.JButton();
        btnExcluirConvenios = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btnAtualizarConvenios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCadastrosUsuarios.setText("Cadastros de Usuários");
        btnCadastrosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosUsuariosActionPerformed(evt);
            }
        });

        btnCadastrosMedicos.setText("Cadastros de Médicos");
        btnCadastrosMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosMedicosActionPerformed(evt);
            }
        });

        btnCadastrosConsultorios.setText("Cadastros de Consultórios");
        btnCadastrosConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosConsultoriosActionPerformed(evt);
            }
        });

        btnCadastrosConvenios.setText("Cadastros Convênios");
        btnCadastrosConvenios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrosConveniosActionPerformed(evt);
            }
        });

        btnHeartClinCadastros.setText("HeartClin");
        btnHeartClinCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeartClinCadastrosActionPerformed(evt);
            }
        });

        PainelPrincipal3.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/002-doctor-1.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/001-doctor.png"))); // NOI18N

        javax.swing.GroupLayout ImagemCadastrosMedicosLayout = new javax.swing.GroupLayout(ImagemCadastrosMedicos);
        ImagemCadastrosMedicos.setLayout(ImagemCadastrosMedicosLayout);
        ImagemCadastrosMedicosLayout.setHorizontalGroup(
            ImagemCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagemCadastrosMedicosLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(39, 39, 39))
        );
        ImagemCadastrosMedicosLayout.setVerticalGroup(
            ImagemCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PainelPrincipal3.add(ImagemCadastrosMedicos, "ImagemCadastrosMedicos");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/006-architecture-and-city.png"))); // NOI18N

        javax.swing.GroupLayout ImagemCadastrosConsultoriosLayout = new javax.swing.GroupLayout(ImagemCadastrosConsultorios);
        ImagemCadastrosConsultorios.setLayout(ImagemCadastrosConsultoriosLayout);
        ImagemCadastrosConsultoriosLayout.setHorizontalGroup(
            ImagemCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagemCadastrosConsultoriosLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(81, 81, 81))
        );
        ImagemCadastrosConsultoriosLayout.setVerticalGroup(
            ImagemCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagemCadastrosConsultoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelPrincipal3.add(ImagemCadastrosConsultorios, "ImagemCadastrosConsultorios");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/005-health.png"))); // NOI18N

        javax.swing.GroupLayout ImagemCadastrosConveniosLayout = new javax.swing.GroupLayout(ImagemCadastrosConvenios);
        ImagemCadastrosConvenios.setLayout(ImagemCadastrosConveniosLayout);
        ImagemCadastrosConveniosLayout.setHorizontalGroup(
            ImagemCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagemCadastrosConveniosLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(74, 74, 74))
        );
        ImagemCadastrosConveniosLayout.setVerticalGroup(
            ImagemCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagemCadastrosConveniosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PainelPrincipal3.add(ImagemCadastrosConvenios, "ImagemCadastrosConvenios");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/004-man.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/003-girl.png"))); // NOI18N

        javax.swing.GroupLayout ImagemCadastrosUsuariosLayout = new javax.swing.GroupLayout(ImagemCadastrosUsuarios);
        ImagemCadastrosUsuarios.setLayout(ImagemCadastrosUsuariosLayout);
        ImagemCadastrosUsuariosLayout.setHorizontalGroup(
            ImagemCadastrosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagemCadastrosUsuariosLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addGap(34, 34, 34))
        );
        ImagemCadastrosUsuariosLayout.setVerticalGroup(
            ImagemCadastrosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagemCadastrosUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ImagemCadastrosUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ImagemCadastrosUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PainelPrincipal3.add(ImagemCadastrosUsuarios, "ImagemCadastrosUsuarios");

        javax.swing.GroupLayout PainelPrincipal1Layout = new javax.swing.GroupLayout(PainelPrincipal1);
        PainelPrincipal1.setLayout(PainelPrincipal1Layout);
        PainelPrincipal1Layout.setHorizontalGroup(
            PainelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipal1Layout.createSequentialGroup()
                .addComponent(PainelPrincipal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnCadastrosConvenios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadastrosConsultorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadastrosMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadastrosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHeartClinCadastros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelPrincipal1Layout.setVerticalGroup(
            PainelPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipal1Layout.createSequentialGroup()
                .addComponent(PainelPrincipal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrosUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrosMedicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrosConsultorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrosConvenios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHeartClinCadastros)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PainelPrincipal2.setLayout(new java.awt.CardLayout());

        PainelCadastrosUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Usuários");

        jLabel3.setText("Usuário:");

        jLabel12.setText("Tipo:");

        jLabel13.setText("Senha:");

        jLabel14.setText("Confirmar Senha:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Registros", "Usuário", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Secretário(a)", "Médico(a)", "Enfermeiro(a)" }));

        jButton2.setText("Pesquisar");

        btnSalvarUsuarios.setText("Salvar");
        btnSalvarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuariosActionPerformed(evt);
            }
        });

        btnCancelarUsuarios.setText("Cancelar");

        btnEditarUsuarios.setText("Editar");
        btnEditarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuariosActionPerformed(evt);
            }
        });

        btnExcluirUsuarios.setText("Excluir");

        btnAtualizarUsuarios.setText("Atualizar");
        btnAtualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastrosUsuarioLayout = new javax.swing.GroupLayout(PainelCadastrosUsuario);
        PainelCadastrosUsuario.setLayout(PainelCadastrosUsuarioLayout);
        PainelCadastrosUsuarioLayout.setHorizontalGroup(
            PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                                        .addComponent(jTextField5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPasswordField2))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosUsuarioLayout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel10)
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        PainelCadastrosUsuarioLayout.setVerticalGroup(
            PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarUsuarios)
                    .addComponent(btnExcluirUsuarios)
                    .addComponent(btnEditarUsuarios)
                    .addComponent(btnCancelarUsuarios)
                    .addComponent(btnAtualizarUsuarios))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        PainelPrincipal2.add(PainelCadastrosUsuario, "PainelCadastrosUsuario");

        PainelCadastrosMedicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvarMedico.setText("Salvar");
        btnSalvarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarMedicoActionPerformed(evt);
            }
        });

        btnCancelarMedico.setText("Cancelar");
        btnCancelarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMedicoActionPerformed(evt);
            }
        });

        btnEditarMedico.setText("Editar");
        btnEditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedicoActionPerformed(evt);
            }
        });

        btnExcluirMedico.setText("Excluir");
        btnExcluirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMedicoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel6.setText("Especialidade:");

        jLabel7.setText("CRM:");

        jLabel8.setText("Duração do Tempo da Consulta:");

        jLabel9.setText("Clínicas:");

        jButton1.setText("Pesquisar");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Médicos");

        jLabel25.setText("ID:");

        TabelaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaMedicosScroll.setViewportView(TabelaMedicos);

        jScrollPane1.setViewportView(TabelaMedicosScroll);

        btnAtualizarMedico.setText("Atualizar");
        btnAtualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelCadastrosMedicosLayout = new javax.swing.GroupLayout(PainelCadastrosMedicos);
        PainelCadastrosMedicos.setLayout(PainelCadastrosMedicosLayout);
        PainelCadastrosMedicosLayout.setHorizontalGroup(
            PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosMedicosLayout.createSequentialGroup()
                        .addGap(0, 228, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(263, 263, 263))
                    .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                        .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDuracaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClinicas))
                            .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCRM))
                            .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIDMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosMedicosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvarMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizarMedico)
                .addGap(53, 53, 53))
        );
        PainelCadastrosMedicosLayout.setVerticalGroup(
            PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosMedicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtIDMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtClinicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuracaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarMedico)
                    .addComponent(btnExcluirMedico)
                    .addComponent(btnEditarMedico)
                    .addComponent(btnCancelarMedico)
                    .addComponent(btnAtualizarMedico))
                .addGap(186, 186, 186))
        );

        PainelPrincipal2.add(PainelCadastrosMedicos, "PainelCadastrosMedicos");

        btnSalvarConsultorios.setText("Salvar");

        btnCancelarConsultorios.setText("Cancelar");

        btnEditarConsultorios.setText("Editar");

        btnExcluirConsultorios.setText("Excluir");

        jLabel17.setText("Nome:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Consultórios");

        jLabel4.setText("Especialidade:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Especialidade"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnAtualizarConsultorios.setText("Atualizar");

        javax.swing.GroupLayout PainelCadastrosConsultoriosLayout = new javax.swing.GroupLayout(PainelCadastrosConsultorios);
        PainelCadastrosConsultorios.setLayout(PainelCadastrosConsultoriosLayout);
        PainelCadastrosConsultoriosLayout.setHorizontalGroup(
            PainelCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosConsultoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConsultoriosLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                    .addGroup(PainelCadastrosConsultoriosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PainelCadastrosConsultoriosLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PainelCadastrosConsultoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConsultoriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarConsultorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirConsultorios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizarConsultorios)
                .addGap(68, 68, 68))
        );
        PainelCadastrosConsultoriosLayout.setVerticalGroup(
            PainelCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConsultoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosConsultoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarConsultorios)
                    .addComponent(btnExcluirConsultorios)
                    .addComponent(btnEditarConsultorios)
                    .addComponent(btnCancelarConsultorios)
                    .addComponent(btnAtualizarConsultorios))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        PainelPrincipal2.add(PainelCadastrosConsultorios, "PainelCadastrosConsultorios");

        PainelCadastrosConvenios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Convênios");

        jLabel5.setText("Nome:");

        jLabel19.setText("Clínica:");

        jLabel20.setText("Registro na ANS:");

        btnSalvarConvenios.setText("Salvar");

        btnCancelarConvenios.setText("Cancelar");

        btnEditarConvenios.setText("Editar");

        btnExcluirConvenios.setText("Excluir");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Clínica", "Registro da ANS"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        btnAtualizarConvenios.setText("Atualizar");

        javax.swing.GroupLayout PainelCadastrosConveniosLayout = new javax.swing.GroupLayout(PainelCadastrosConvenios);
        PainelCadastrosConvenios.setLayout(PainelCadastrosConveniosLayout);
        PainelCadastrosConveniosLayout.setHorizontalGroup(
            PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosConveniosLayout.createSequentialGroup()
                .addGroup(PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelCadastrosConveniosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelCadastrosConveniosLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField12))
                            .addGroup(PainelCadastrosConveniosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConveniosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConveniosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConveniosLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelCadastrosConveniosLayout.createSequentialGroup()
                        .addComponent(btnSalvarConvenios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarConvenios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditarConvenios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirConvenios, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizarConvenios)
                        .addGap(62, 62, 62))))
        );
        PainelCadastrosConveniosLayout.setVerticalGroup(
            PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCadastrosConveniosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelCadastrosConveniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarConvenios)
                    .addComponent(btnExcluirConvenios)
                    .addComponent(btnEditarConvenios)
                    .addComponent(btnCancelarConvenios)
                    .addComponent(btnAtualizarConvenios))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        PainelPrincipal2.add(PainelCadastrosConvenios, "PainelCadastrosConvenios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        setSize(new java.awt.Dimension(849, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosUsuariosActionPerformed
        mostrarTelas("PainelCadastrosUsuario");
        mostrarImagem("ImagemCadastrosUsuarios");
    }//GEN-LAST:event_btnCadastrosUsuariosActionPerformed

    private void btnCadastrosMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosMedicosActionPerformed
        mostrarTelas("PainelCadastrosMedicos");
        mostrarImagem("ImagemCadastrosMedicos");
        preencherTabela("Select * from MEDICOS ORDER BY ID_MEDICO");


    }//GEN-LAST:event_btnCadastrosMedicosActionPerformed

    private void btnCadastrosConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosConsultoriosActionPerformed
        mostrarTelas("PainelCadastrosConsultorios");
        mostrarImagem("ImagemCadastrosConsultorios");
    }//GEN-LAST:event_btnCadastrosConsultoriosActionPerformed

    private void btnCadastrosConveniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrosConveniosActionPerformed
        mostrarTelas("PainelCadastrosConvenios");
        mostrarImagem("ImagemCadastrosConvenios");
    }//GEN-LAST:event_btnCadastrosConveniosActionPerformed

    private void btnSalvarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuariosActionPerformed


    }//GEN-LAST:event_btnSalvarUsuariosActionPerformed

    private void btnSalvarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMedicoActionPerformed
        if (txtNomeMedico.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Nome!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtNomeMedico.requestFocus();
            return;
        }
        if (txtEspecialidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a Especialidade!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtEspecialidade.requestFocus();
            return;
        }
        if (txtCRM.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CRM!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtCRM.requestFocus();
            return;
        }
        if (txtDuracaoConsulta.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Informe o Tempo de Duração da Consulta!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtDuracaoConsulta.requestFocus();
            return;
        }

        try {
            DatabaseConnection databaseConnection = new DatabaseConnection();

            String query = "INSERT INTO MEDICOS (ID_MEDICO, NOME_MEDICO, ESPECIALIDADE, CRM, DURACAO_CONSULTA) VALUES(ID.NEXTVAL, ?, ?, ?, ?)";

            Connection con = databaseConnection.Conexao();
            PreparedStatement pst = con.prepareStatement(query);

            int count = 0;
            pst.setString(++count, txtNomeMedico.getText());
            pst.setString(++count, txtEspecialidade.getText());
            pst.setString(++count, txtCRM.getText());
            pst.setString(++count, txtDuracaoConsulta.getSelectedItem().toString());

            pst.execute();

            pst.close();
            JOptionPane.showMessageDialog(null, "Cadastro Salvo!");

            txtNomeMedico.setText(null);
            txtEspecialidade.setText(null);
            txtCRM.setText(null);
            txtDuracaoConsulta.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no cadastro!");
            System.out.println(ex.getMessage());
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        preencherTabela("Select * from MEDICOS ORDER BY ID_MEDICO");
    }//GEN-LAST:event_btnSalvarMedicoActionPerformed

    private void btnCancelarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMedicoActionPerformed
        
        txtIDMedico.setText(null);
        txtNomeMedico.setText(null);
        txtEspecialidade.setText(null);
        txtCRM.setText(null);
        txtDuracaoConsulta.setSelectedIndex(0);

        JOptionPane.showMessageDialog(null, "Cadastro Cancelado!");
    }//GEN-LAST:event_btnCancelarMedicoActionPerformed

    private void btnEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedicoActionPerformed

        BigDecimal numero = (BigDecimal) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 0);
        txtIDMedico.setText(numero.toString());

        String nome = (String) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 1);
        txtNomeMedico.setText(nome);
        
        String especialidade = (String) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 2);
        txtEspecialidade.setText(especialidade);
        
        String crm = (String) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 3);
        txtCRM.setText(crm);
        
        String duracaoConsulta = (String) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 4);
        if (duracaoConsulta.equals("30 Minutos"))
            txtDuracaoConsulta.setSelectedIndex(1);
        else if (duracaoConsulta.equals("35 Minutos"))
            txtDuracaoConsulta.setSelectedIndex(2);
        else if (duracaoConsulta.equals("40 Minutos"))
            txtDuracaoConsulta.setSelectedIndex(3);
        else if (duracaoConsulta.equals("45 Minutos"))
            txtDuracaoConsulta.setSelectedIndex(4);
        else if (duracaoConsulta.equals("1 Hora"))
            txtDuracaoConsulta.setSelectedIndex(5);
        else
          txtDuracaoConsulta.setSelectedIndex(6);
        
        String clinicas = (String) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 5);
        txtClinicas.setText(clinicas);
    }//GEN-LAST:event_btnEditarMedicoActionPerformed

    private void btnAtualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarUsuariosActionPerformed

    }//GEN-LAST:event_btnAtualizarUsuariosActionPerformed

    private void btnEditarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarUsuariosActionPerformed

    private void btnAtualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarMedicoActionPerformed
          if (txtNomeMedico.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Nome!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtNomeMedico.requestFocus();
            return;
        }
        if (txtEspecialidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a Especialidade!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtEspecialidade.requestFocus();
            return;
        }
        if (txtCRM.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CRM!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtCRM.requestFocus();
            return;
        }

        if (txtDuracaoConsulta.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Tempo de Duração da Consulta!", "Campo em branco", JOptionPane.YES_NO_OPTION);
            txtDuracaoConsulta.requestFocus();
            return;
        }
         try {
            DatabaseConnection databaseConnection = new DatabaseConnection();

            String query = "UPDATE MEDICOS SET NOME_MEDICO= '"+txtNomeMedico.getText()+"' ,ESPECIALIDADE= '"+txtEspecialidade.getText()+"', CRM= "+txtCRM.getText()+", DURACAO_CONSULTA= '"+txtDuracaoConsulta.getSelectedItem().toString()+"' WHERE ID_MEDICO= "+txtIDMedico.getText()+"";
            Connection con = databaseConnection.Conexao();
            PreparedStatement pst = con.prepareStatement(query);
            pst.execute();

            pst.close();
            JOptionPane.showMessageDialog(null, "Cadastro Alterado!");
            
            txtIDMedico.setText(null);
            txtNomeMedico.setText(null);
            txtEspecialidade.setText(null);
            txtCRM.setText(null);
            txtDuracaoConsulta.setSelectedIndex(0);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na Alteração!");
            System.out.println(ex.getMessage());
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
         
        preencherTabela("Select * from MEDICOS ORDER BY ID_MEDICO");
    }//GEN-LAST:event_btnAtualizarMedicoActionPerformed

    private void btnExcluirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMedicoActionPerformed
        try {
            DatabaseConnection databaseConnection = new DatabaseConnection();

            if(JOptionPane.showConfirmDialog(null, "Informe o Tempo de Duração da Consulta!", "Campo em branco", JOptionPane.YES_NO_OPTION) <= 0 ){
                BigDecimal numero = (BigDecimal) TabelaMedicos.getModel().getValueAt(TabelaMedicos.getSelectedRow(), 0);
                String query = "DELETE FROM MEDICOS WHERE ID_MEDICO= '" + numero.toString() + "'";
                Connection con = databaseConnection.Conexao();
                PreparedStatement pst = con.prepareStatement(query);
                pst.execute();

                pst.close();
                JOptionPane.showMessageDialog(null, "Cadastro Excluído!");
            } 

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na Exclusão!");
            System.out.println(ex.getMessage());
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
         
        preencherTabela("Select * from MEDICOS ORDER BY ID_MEDICO");
        
    }//GEN-LAST:event_btnExcluirMedicoActionPerformed

    private void btnHeartClinCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeartClinCadastrosActionPerformed
        HeartClin heartClin = new HeartClin();
        heartClin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHeartClinCadastrosActionPerformed

    private DefaultTableModel modeloTabela = new DefaultTableModel();

    public JTextField getTxtNomeMedico() {
        return txtNomeMedico;
    }

    public void setTxtNomeMedico(JTextField txtNomeMedico) {
        this.txtNomeMedico = txtNomeMedico;
    }
    Connection connection = null;

    public void preencherTabela(String Sql) {
        connection = databaseConnection.Conexao();
        try {
            DatabaseConnection databaseConnection = new DatabaseConnection();
            Connection con = databaseConnection.Conexao();
            PreparedStatement pst = connection.prepareStatement(Sql);
            ResultSet rs = pst.executeQuery();

            TabelaMedicos.setModel(DbUtils.resultSetToTableModel(rs));
            databaseConnection.conexao.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + ex.getCause() + " + Erro ao Buscar Médicos!");
        }

    }

    public void preencherComboClinica(String Sql) {
        connection = databaseConnection.Conexao();
        
        try {
            DatabaseConnection databaseConnection = new DatabaseConnection();
            Connection con = databaseConnection.Conexao();
            PreparedStatement pst = connection.prepareStatement(Sql);
            ResultSet rs = pst.executeQuery();

            ArrayList<String> resultados = new ArrayList<String>();

            while (rs.next()) {
                resultados.add(rs.getString(0));
            }

            String[] vetor = (String[]) resultados.toArray();

            txtDuracaoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(vetor));

            TabelaMedicos.setModel(DbUtils.resultSetToTableModel(rs));
            databaseConnection.conexao.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + ex.getCause() + " + Erro ao Buscar Médicos!");
        }

    }

    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ImagemCadastrosConsultorios;
    private javax.swing.JPanel ImagemCadastrosConvenios;
    private javax.swing.JPanel ImagemCadastrosMedicos;
    private javax.swing.JPanel ImagemCadastrosUsuarios;
    private javax.swing.JPanel PainelCadastrosConsultorios;
    private javax.swing.JPanel PainelCadastrosConvenios;
    private javax.swing.JPanel PainelCadastrosMedicos;
    private javax.swing.JPanel PainelCadastrosUsuario;
    private javax.swing.JPanel PainelPrincipal1;
    private javax.swing.JPanel PainelPrincipal2;
    private javax.swing.JPanel PainelPrincipal3;
    private javax.swing.JTable TabelaMedicos;
    private javax.swing.JScrollPane TabelaMedicosScroll;
    private javax.swing.JButton btnAtualizarConsultorios;
    private javax.swing.JButton btnAtualizarConvenios;
    private javax.swing.JButton btnAtualizarMedico;
    private javax.swing.JButton btnAtualizarUsuarios;
    private javax.swing.JButton btnCadastrosConsultorios;
    private javax.swing.JButton btnCadastrosConvenios;
    private javax.swing.JButton btnCadastrosMedicos;
    private javax.swing.JButton btnCadastrosUsuarios;
    private javax.swing.JButton btnCancelarConsultorios;
    private javax.swing.JButton btnCancelarConvenios;
    private javax.swing.JButton btnCancelarMedico;
    private javax.swing.JButton btnCancelarUsuarios;
    private javax.swing.JButton btnEditarConsultorios;
    private javax.swing.JButton btnEditarConvenios;
    private javax.swing.JButton btnEditarMedico;
    private javax.swing.JButton btnEditarUsuarios;
    private javax.swing.JButton btnExcluirConsultorios;
    private javax.swing.JButton btnExcluirConvenios;
    private javax.swing.JButton btnExcluirMedico;
    private javax.swing.JButton btnExcluirUsuarios;
    private javax.swing.JButton btnHeartClinCadastros;
    private javax.swing.JButton btnSalvarConsultorios;
    private javax.swing.JButton btnSalvarConvenios;
    private javax.swing.JButton btnSalvarMedico;
    private javax.swing.JButton btnSalvarUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtCRM;
    private javax.swing.JTextField txtClinicas;
    private javax.swing.JComboBox<String> txtDuracaoConsulta;
    private javax.swing.JTextField txtEspecialidade;
    private javax.swing.JTextField txtIDMedico;
    private javax.swing.JTextField txtNomeMedico;
    // End of variables declaration//GEN-END:variables
}
